# Generated by Django 2.1 on 2020-02-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flagapp.models.flag


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.CharField(default=flagapp.models.flag.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateField(db_index=True)),
                ('message', models.CharField(max_length=250)),
                ('updated_at', models.DateField(db_index=True)),
                ('status', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('Accidentally enter', 'Accidentally enter'), ('Duplicate encounter', 'Duplicate encounter'), ('Incorrect patient', 'Incorrect patient'), ('Incorrect user', 'Incorrect user'), ('Other', 'Other')], default='Blank', max_length=50)),
                ('other', models.CharField(default='', max_length=250)),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_author', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
