# Generated by Django 2.1 on 2020-02-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagapp', '0002_auto_20200203_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='object_id',
            field=models.CharField(max_length=200),
        ),
    ]
