# Generated by Django 2.1 on 2020-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagapp', '0003_auto_20200203_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='patient_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
