# Generated by Django 2.0 on 2019-09-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0004_remove_treatment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='uid',
            new_name='id',
        ),
    ]
