# Generated by Django 2.0 on 2019-11-06 06:31

from django.db import migrations, models
import visualizationapp.models.visualization


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.CharField(default=visualizationapp.models.visualization.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('patiend_id', models.CharField(max_length=60)),
                ('encounter_id', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=60)),
                ('activities_id', models.CharField(max_length=60)),
                ('geography_id', models.CharField(max_length=60)),
                ('ext', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('seal', models.BooleanField(default=False)),
                ('sdf', models.BooleanField(default=False)),
                ('fv', models.BooleanField(default=False)),
                ('refer_hp', models.BooleanField(default=False)),
                ('refer_hyg', models.BooleanField(default=False)),
                ('refer_dent', models.BooleanField(default=False)),
                ('refer_dr', models.BooleanField(default=False)),
                ('refer_other', models.BooleanField(default=False)),
                ('carries_risk', models.CharField(max_length=60)),
                ('decayed_primary_teeth', models.BooleanField(default=False)),
                ('decayed_permanent_teeth', models.BooleanField(default=False)),
                ('cavity_permanent_posterior_teeth', models.BooleanField(default=False)),
                ('cavity_permanent_anterior_teeth', models.BooleanField(default=False)),
                ('active_infection', models.BooleanField(default=False)),
                ('reversible_pulpitis', models.BooleanField(default=False)),
                ('need_art_filling', models.BooleanField(default=False)),
                ('need_extraction', models.BooleanField(default=False, verbose_name='need extraction')),
                ('need_sdf', models.BooleanField(default=False)),
            ],
        ),
    ]
