# Generated by Django 2.0 on 2019-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='encounter_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='patiend_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
