# Generated by Django 2.0 on 2019-11-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0002_auto_20191106_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='carries_risk',
            field=models.CharField(default='', max_length=60),
        ),
    ]
