# Generated by Django 2.0 on 2019-11-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0003_auto_20191108_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualization',
            old_name='ext',
            new_name='exo',
        ),
    ]
