# Generated by Django 2.0 on 2019-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0004_auto_20191108_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
