# Generated by Django 2.0 on 2019-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0005_visualization_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='patiend_id',
            field=models.CharField(max_length=60),
        ),
    ]
