# Generated by Django 2.0 on 2019-11-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0007_auto_20191120_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='decayed_permanent_teeth_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='decayed permanent teeth'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='decayed_primary_teeth_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='decayed primary teeth'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='decayed_permanent_teeth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='decayed_primary_teeth',
            field=models.BooleanField(default=False),
        ),
    ]
