# Generated by Django 2.0 on 2019-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0009_auto_20191122_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='need_sealant',
            field=models.BooleanField(default=False),
        ),
    ]
