# Generated by Django 2.0 on 2019-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0010_visualization_need_sealant'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='reason_for_visit',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='visualization',
            name='referral_type',
            field=models.CharField(default='', max_length=60),
        ),
    ]
