# Generated by Django 2.1 on 2020-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0012_auto_20200113_1435'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visualization',
            name='visualizati_activit_28d1e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='visualization',
            name='visualizati_created_31e5da_idx',
        ),
        migrations.AlterField(
            model_name='visualization',
            name='active_infection',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='activities_id',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='age',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='art',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='carries_risk',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='cavity_permanent_anterior_teeth',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='cavity_permanent_posterior_teeth',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='created_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='decayed_permanent_teeth',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='decayed_permanent_teeth_number',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='decayed permanent teeth'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='decayed_primary_teeth',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='decayed_primary_teeth_number',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='decayed primary teeth'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='encounter_id',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='exo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='fv',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='gender',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='geography_id',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='need_art_filling',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='need_extraction',
            field=models.BooleanField(db_index=True, default=False, verbose_name='need extraction'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='need_sdf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='need_sealant',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='patiend_id',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='reason_for_visit',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='refer_dent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='refer_dr',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='refer_hp',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='refer_hyg',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='refer_other',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='referral_type',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='reversible_pulpitis',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='sdf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='sdf_whole_mouth',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='seal',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
