# Generated by Django 2.1 on 2020-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0013_auto_20200113_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='activity_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visualization',
            name='encounter_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visualization',
            name='geography_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visualization',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
