# Generated by Django 2.1 on 2020-01-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0014_auto_20200114_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='encounter_type',
        ),
    ]
