# Generated by Django 2.1 on 2020-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0015_remove_visualization_encounter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='author',
            field=models.CharField(default='', max_length=60),
        ),
    ]
