# Generated by Django 2.1 on 2020-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0016_visualization_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='activities_id',
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
    ]
