# Generated by Django 2.1 on 2020-08-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0019_auto_20200809_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='encounter_id',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
