# Generated by Django 2.1 on 2020-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0020_auto_20200810_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='art',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='exo',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='sdf',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='seal',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
