# Generated by Django 2.1 on 2021-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0021_auto_20201021_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
