# Generated by Django 2.1 on 2021-04-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0022_visualization_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='need_dentist_or_hygienist',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visualization',
            name='need_fv',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
