# Generated by Django 2.1 on 2022-02-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0023_auto_20210429_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='recall_date',
            field=models.DateField(null=True),
        ),
    ]
