# Generated by Django 2.1 on 2022-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0024_visualization_recall_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='recall_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
