# Generated by Django 2.1 on 2022-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizationapp', '0025_auto_20220225_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='recall_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
