# Generated by Django 2.0 on 2019-06-25 05:02

from django.db import migrations, models
import patientapp.models.patient


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(default=patientapp.models.patient.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30)),
                ('phone', models.CharField(max_length=17, unique=True, verbose_name='phone number')),
                ('education', models.CharField(max_length=255, verbose_name='education level')),
            ],
        ),
    ]
