# Generated by Django 2.0 on 2019-08-15 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import patientapp.models.patient


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(default=patientapp.models.patient.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('age', models.PositiveIntegerField(editable=False, null=True)),
                ('phone', models.CharField(max_length=17, unique=True, verbose_name='phone number')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='register_date')),
                ('latitude', models.DecimalField(decimal_places=8, default=12, help_text='author latitude', max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, default=12, help_text='author longitude', max_digits=12)),
                ('district', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('municipality_type', models.CharField(max_length=50)),
                ('ward', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='ward_number')),
                ('activity_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_area', to='addressapp.ActivityArea')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_obj', to=settings.AUTH_USER_MODEL)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_geography', to='addressapp.Geography')),
            ],
        ),
    ]
