# Generated by Django 2.0 on 2019-08-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_geography', to='addressapp.Geography'),
        ),
    ]
