# Generated by Django 2.0 on 2019-08-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='municipality_type',
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.District'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.Municipality'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.Ward'),
        ),
    ]
