# Generated by Django 2.0 on 2019-07-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0001_initial'),
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='activity_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_area', to='addressapp.ActivityArea'),
        ),
        migrations.AddField(
            model_name='patient',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_geography', to='addressapp.Geography'),
        ),
    ]
