# Generated by Django 2.0 on 2019-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_patient_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=150, null=True, verbose_name='city/village'),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=150, null=True, verbose_name='state/province'),
        ),
    ]
