# Generated by Django 2.0 on 2019-09-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientapp', '0003_auto_20190829_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
