# Generated by Django 2.0 on 2019-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20190817_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
