# Generated by Django 2.0 on 2019-06-25 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20190625_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='register_date'),
        ),
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=12, help_text='author latitude', max_digits=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=12, help_text='author longitude', max_digits=12),
        ),
    ]
