# Generated by Django 2.0 on 2019-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_auto_20190902_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='updated_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
