# Generated by Django 2.0 on 2019-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_auto_20190625_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='register_date'),
        ),
    ]
