# Generated by Django 2.0 on 2019-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_auto_20190911_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
