# Generated by Django 2.0 on 2019-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_auto_20190911_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
    ]
