# Generated by Django 2.0 on 2019-09-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_remove_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='uid',
            new_name='id',
        ),
    ]
