# Generated by Django 2.1 on 2020-10-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0002_auto_20200113_1501'),
        ('patientapp', '0007_auto_20200601_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.ActivityArea'),
        ),
    ]
