# Generated by Django 2.0 on 2019-09-19 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_auto_20190912_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recall_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='recall_geography',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='recall_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
