# Generated by Django 2.1 on 2021-02-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_auto_20210219_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.ActivityArea'),
        ),
    ]
