# Generated by Django 2.0 on 2019-08-20 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encounterapp.models.encounter
import encounterapp.models.history
import encounterapp.models.refer
import encounterapp.models.screeing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(default=encounterapp.models.encounter.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('encounter_type', models.CharField(choices=[('Checkup / Screening', 'Checkup / Screening'), ('Relief of pain', 'Relief of pain'), ('Continuation of treatment plan', 'Continuation of treatment plan'), ('Other Problem', 'Other Problem')], max_length=150, verbose_name='encounter type')),
                ('updated_at', models.DateTimeField(default=encounterapp.models.encounter.default_time)),
                ('activity_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_area', to='addressapp.ActivityArea')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('geography', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_geography', to='addressapp.Ward')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(default=encounterapp.models.history.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('bleeding', models.BooleanField(default=False, verbose_name='bleeding problem')),
                ('diabetes', models.BooleanField(default=False)),
                ('liver', models.BooleanField(default=False, verbose_name='liver problem')),
                ('fever', models.BooleanField(default=False, verbose_name='rheumatic fever')),
                ('seizures', models.BooleanField(default=False, verbose_name='epilepsy or seizures')),
                ('hepatitis', models.BooleanField(default=False, verbose_name='hepatitis b or b')),
                ('hiv', models.BooleanField(default=False)),
                ('no_allergic', models.BooleanField(default=False)),
                ('allergie', models.TextField(blank=True, null=True)),
                ('other', models.CharField(blank=True, max_length=255)),
                ('no_underlying_medical', models.BooleanField(default=False, verbose_name='no underlying medical condition')),
                ('not_taking_medication', models.BooleanField(default=False, verbose_name='not taking any medications')),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('no_medication', models.BooleanField(default=False)),
                ('encounter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='encounterapp.Encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(default=encounterapp.models.refer.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('no_referal', models.BooleanField(default=False, verbose_name='no referal')),
                ('health_post', models.BooleanField(default=False, verbose_name='health post')),
                ('dentist', models.BooleanField(default=False)),
                ('physician', models.BooleanField(default=False, verbose_name='general physician')),
                ('hygienist', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=255)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('encounter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer', to='encounterapp.Encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Screeing',
            fields=[
                ('id', models.CharField(blank=True, max_length=200)),
                ('uid', models.CharField(default=encounterapp.models.screeing.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('caries_risk', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], max_length=30, verbose_name='caries risk')),
                ('primary_teeth', models.PositiveIntegerField(verbose_name='decayed primary teeth')),
                ('permanent_teeth', models.PositiveIntegerField(verbose_name='decayed permanent teeth')),
                ('postiror_teeth', models.BooleanField(default=False, verbose_name='cavity permanent postiror teeth')),
                ('anterior_teeth', models.BooleanField(default=False, verbose_name='cavity permanent anterior teeth')),
                ('infection', models.BooleanField(default=False, verbose_name='active infection')),
                ('reversible_pulpitis', models.BooleanField(default=False, verbose_name='mouth pain due to reversible pulpitis')),
                ('art', models.BooleanField(default=False, verbose_name='Atraumatic restorative treatment')),
                ('extraction', models.BooleanField(default=False, verbose_name='need extraction')),
                ('refernal_kdh', models.BooleanField(default=False, verbose_name='need refernal kdh')),
                ('encounter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screeing', to='encounterapp.Encounter')),
            ],
        ),
    ]
