# Generated by Django 2.0 on 2019-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='other_detail',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
