# Generated by Django 2.0 on 2019-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='no_allergic',
            new_name='no_allergies',
        ),
        migrations.RemoveField(
            model_name='history',
            name='allergie',
        ),
        migrations.AddField(
            model_name='history',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
