# Generated by Django 2.0 on 2019-06-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='encounterapp.Encounter'),
        ),
        migrations.AlterField(
            model_name='refer',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer', to='encounterapp.Encounter'),
        ),
        migrations.AlterField(
            model_name='screeing',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screeing', to='encounterapp.Encounter'),
        ),
    ]
