# Generated by Django 2.0 on 2019-09-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='epilepsy_or_seizures',
            new_name='seizuers_or_epilepsy',
        ),
        migrations.RenameField(
            model_name='refer',
            old_name='physician',
            new_name='general_physician',
        ),
    ]
