# Generated by Django 2.0 on 2019-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('screeing', 'Checkup/Screeing'), ('pain', 'Relief of pain'), ('treatment plan', 'Continuation of treatment plan'), ('other', 'Other Problem')], max_length=30, verbose_name='encounter type'),
        ),
    ]
