# Generated by Django 2.0 on 2019-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='refer',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
