# Generated by Django 2.0 on 2019-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0002_auto_20190820_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeing',
            name='caries_risk',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], max_length=30, verbose_name='caries risk'),
        ),
    ]
