# Generated by Django 2.0 on 2019-08-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0002_encounter_other_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_geography', to='addressapp.Geography'),
        ),
    ]
