# Generated by Django 2.0 on 2019-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0002_auto_20190924_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='other_detail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='history',
            name='allergies',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='medications',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='other',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='refer',
            name='other',
            field=models.CharField(default='', max_length=255),
        ),
    ]
