# Generated by Django 2.0 on 2019-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0002_auto_20190820_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('Checkup / Screening', 'Checkup / Screening'), ('Relief of pain', 'Relief of pain'), ('Continuation of treatment plan', 'Continuation of treatment plan'), ('Other Problem', 'Other Problem')], max_length=150, verbose_name='encounter type'),
        ),
    ]
