# Generated by Django 2.0 on 2019-06-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0002_auto_20190628_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeing',
            old_name='risk',
            new_name='caries_risk',
        ),
    ]
