# Generated by Django 2.0 on 2019-08-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0003_auto_20190822_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeing',
            name='blood_pressure',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Normal', 'Normal')], default='Normal', max_length=15),
        ),
    ]
