# Generated by Django 2.0 on 2019-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0003_auto_20190822_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeing',
            name='high_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeing',
            name='low_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeing',
            name='thyroid',
            field=models.BooleanField(default=False),
        ),
    ]
