# Generated by Django 2.0 on 2019-06-28 09:33

from django.db import migrations, models
import encounterapp.models.encounter


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0003_auto_20190628_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='update_date',
            field=models.DateTimeField(default=encounterapp.models.encounter.default_time),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
