# Generated by Django 2.0 on 2019-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0003_auto_20190820_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeing',
            name='infection',
        ),
        migrations.RemoveField(
            model_name='screeing',
            name='refernal_kdh',
        ),
        migrations.AddField(
            model_name='screeing',
            name='need_sdf',
            field=models.BooleanField(default=False, verbose_name='need sdf'),
        ),
        migrations.AddField(
            model_name='screeing',
            name='need_sealant',
            field=models.BooleanField(default=False, verbose_name='need sealant'),
        ),
    ]
