# Generated by Django 2.0 on 2019-07-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0004_auto_20190628_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='no_medication',
            field=models.BooleanField(default=False),
        ),
    ]
