# Generated by Django 2.0 on 2019-09-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounterapp', '0004_auto_20190828_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_encounter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='refer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_refer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refer',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='screeing',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_screeing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screeing',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
