# Generated by Django 2.0 on 2019-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0004_auto_20190820_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeing',
            name='active_infection',
            field=models.BooleanField(default=False),
        ),
    ]
