# Generated by Django 2.0 on 2019-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0005_auto_20190902_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='refer',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
