# Generated by Django 2.0 on 2019-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0006_auto_20190911_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.RemoveField(
            model_name='refer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='screeing',
            name='id',
        ),
    ]
