# Generated by Django 2.0 on 2019-09-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0007_auto_20190912_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='refer',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='uid',
            new_name='id',
        ),
    ]
