# Generated by Django 2.0 on 2019-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0008_auto_20190912_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='bleeding',
            new_name='blood_disorder',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='seizures',
            new_name='epilepsy_or_seizures',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='liver',
            new_name='liver_problem',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='medication',
            new_name='medications',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='no_medication',
            new_name='no_medications',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='no_underlying_medical',
            new_name='no_underlying_medical_condition',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='not_taking_medication',
            new_name='not_taking_any_medications',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='fever',
            new_name='rheumatic_fever',
        ),
        migrations.RemoveField(
            model_name='history',
            name='hepatitis',
        ),
        migrations.AddField(
            model_name='history',
            name='hepatitis_b_or_c',
            field=models.BooleanField(default=False, verbose_name='hepatitis b or c'),
        ),
    ]
