# Generated by Django 2.0 on 2019-09-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0009_auto_20190913_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeing',
            old_name='anterior_teeth',
            new_name='cavity_permanent_anterior_teeth',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='postiror_teeth',
            new_name='cavity_permanent_postiror_teeth',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='permanent_teeth',
            new_name='decayed_permanent_teeth',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='primary_teeth',
            new_name='decayed_primary_teeth',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='art',
            new_name='need_art_filling',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='extraction',
            new_name='need_extraction',
        ),
        migrations.RenameField(
            model_name='screeing',
            old_name='thyroid',
            new_name='thyroid_disorder',
        ),
    ]
