# Generated by Django 2.0 on 2019-09-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0010_auto_20190913_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeing',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='encounterapp.Encounter'),
        ),
    ]
