# Generated by Django 2.0 on 2019-09-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0011_auto_20190916_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='encounter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='encounterapp.Encounter'),
        ),
    ]
