# Generated by Django 2.0 on 2019-09-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0012_auto_20190916_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='encounter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='encounterapp.Encounter'),
        ),
    ]
