# Generated by Django 2.0 on 2019-09-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0013_auto_20190917_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='encounter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='encounterapp.Encounter'),
        ),
        migrations.AlterField(
            model_name='screeing',
            name='encounter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='encounterapp.Encounter'),
        ),
    ]
