# Generated by Django 2.1 on 2021-03-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0037_encounter_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.ActivityArea'),
        ),
    ]
