# Generated by Django 2.1 on 2021-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0038_auto_20210302_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeing',
            name='need_dentist_or_hygienist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeing',
            name='need_fv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeing',
            name='soft_issue_finding',
            field=models.TextField(null=True),
        ),
    ]
