# Generated by Django 2.1 on 2021-04-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0039_auto_20210329_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifydelete',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
