# Generated by Django 2.0 on 2019-07-01 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150, verbose_name='activity area')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='city/village')),
                ('state', models.CharField(max_length=150, verbose_name='state/province')),
                ('country', models.CharField(max_length=120)),
                ('street_address', models.CharField(max_length=255)),
                ('ward', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='ward no')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
