# Generated by Django 2.0 on 2019-08-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='municipality',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
