# Generated by Django 2.0 on 2019-08-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='municipality_type',
        ),
    ]
