# Generated by Django 2.0 on 2019-08-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityarea',
            name='area',
            field=models.CharField(choices=[('Health Post', 'Health Post'), ('School Seminar', 'School Seminar'), ('Community Outreach', 'Community Outreach'), ('Training', 'Training')], max_length=30),
        ),
    ]
