# Generated by Django 2.0 on 2019-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='ward_name',
        ),
        migrations.AddField(
            model_name='ward',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
