# Generated by Django 2.0 on 2019-07-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
