# Generated by Django 2.0 on 2019-08-16 05:56

import addressapp.models.address
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0002_remove_geography_municipality_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(default=addressapp.models.address.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.CharField(default=addressapp.models.address.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('municipality', models.CharField(max_length=50)),
                ('municipality_type', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_municipality', to='addressapp.District')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(default=addressapp.models.address.keygenerator, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('ward', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='ward_number')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_ward', to='addressapp.Municipality')),
            ],
        ),
    ]
