# Generated by Django 2.0 on 2019-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0002_geography_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityarea',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
