# Generated by Django 2.0 on 2019-08-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0005_auto_20190816_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressapp.District'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressapp.Municipality'),
        ),
    ]
