# Generated by Django 2.0 on 2019-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0003_activityarea_status'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(to='addressapp.Geography'),
        ),
    ]
