# Generated by Django 2.0 on 2019-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
