# Generated by Django 2.0 on 2019-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth1',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth10',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth11',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth12',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth13',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth14',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth15',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth16',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth17',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth18',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth19',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth2',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth20',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth3',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth4',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth5',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth6',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth7',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth8',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='primary_teeth9',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth1',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth10',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth11',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth12',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth13',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth14',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth15',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth16',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth17',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth18',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth19',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth2',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth20',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth21',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth22',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth23',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth24',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth25',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth26',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth27',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth28',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth29',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth3',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth30',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth31',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth32',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth4',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth5',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth6',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth7',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth8',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth9',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR'), ('SMART', 'SMART')], default='NONE', max_length=30),
        ),
    ]
