# Generated by Django 2.0 on 2019-07-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0002_auto_20190718_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth1',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth10',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth11',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth12',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth13',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth14',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth15',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth16',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth17',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth18',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth19',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth2',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth20',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth3',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth4',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth5',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth6',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth7',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth8',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='primary_teeth9',
            field=models.CharField(choices=[('None', 'None'), ('SDF', 'SDF'), ('SEAL', 'SEAL'), ('ART', 'ART'), ('EXO', 'EXO'), ('UNTR', 'UNTR')], default='None', max_length=30),
        ),
    ]
