# Generated by Django 2.0 on 2019-09-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0002_auto_20190902_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
