# Generated by Django 2.0 on 2019-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0003_auto_20190911_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='id',
        ),
    ]
