# Generated by Django 2.0 on 2019-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0005_auto_20190912_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='fluoride_varnish',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_complete',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='whole_mouth',
        ),
        migrations.AddField(
            model_name='treatment',
            name='fv_applied',
            field=models.BooleanField(default=False, verbose_name='fluoride varnish'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='sdf_whole_mouth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_plan_complete',
            field=models.BooleanField(default=False, verbose_name='treatment complete'),
        ),
    ]
