# Generated by Django 2.0 on 2019-09-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0006_auto_20190913_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='encounter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='encounterapp.Encounter'),
        ),
    ]
