# Generated by Django 2.0 on 2019-09-17 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentapp', '0007_auto_20190917_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
